# Configurações do MongoDB
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: registration

# Folder to import files
file:
  import:
    input:
      path: "C:/Files/Input"
    output:
      path: "C:/Files/Output"

# Configurações da API
api:
  health:
    url: http://localhost:8080/api/health
